### PR TITLE
default --ncpu

### PR DESCRIPTION
**Pull request by botteon**
getcpus() returns half of the cpu of os.cpu_count() in leiden

### CODE REVIEW

**Comment by botteon** [comment]
aah actually the number of threads is halved by getcpus because of this line 

https://github.com/rvweeren/lofar_facet_selfcal/blob/593f0c5b6107ad623812bed993a5ada85ecef486/sub-sources-outside-region.py#L32

which does not enable hyperthreading. I am not sure if there is a reason why logical=False is preferred (@tikk3r?). I've noticed this because the script was running slower than usual and I found out that half of the threads were used. I hadn't run the script in a while so don't know if there were changes that could make it slower (I was extracting a target from a single LoTSS pointing)

**Comment by rvweeren** [comment]
If I remember correctly, having it like this (so halving the number of CPUs) was convenient for nodes with less RAM. Because otherwise DDFacet ran out of RAM when on certain nodes when --npcu was left to the default.

**Comment by tikk3r** [comment]
> aah actually the number of threads is halved by getcpus because of this line
> 
> https://github.com/rvweeren/lofar_facet_selfcal/blob/593f0c5b6107ad623812bed993a5ada85ecef486/sub-sources-outside-region.py#L32
> 
> which does not enable hyperthreading. I am not sure if there is a reason why logical=False is preferred (@tikk3r?). I've noticed this because the script was running slower than usual and I found out that half of the threads were used. I hadn't run the script in a while so don't know if there were changes that could make it slower (I was extracting a target from a single LoTSS pointing)

Looking at the git blame this has been in there for at least 2 years, so I'm not sure if it is directly responsible for a recent slowdown. I'm not sure why it is set to only take physical cores. Maybe it was seen that hyperthreading didn't really help, or caused memory issues like @rvweeren mentions.

**Comment by botteon** [comment]
That's possible, but it may not be the full story. I am not even sure if this is a _recent_ slowdown, as mentioned by @tikk3r.

Yes, the bit of code about --ncpu has been like this at least for 2 years now, namely since when @rvweeren created this repository, importing the sub-sources-outside-region.py script from the ddf-pipeline repository here. I guess that when you did that, you changed the --ncpu line (and never touched it again since then). Note that in the ddf-pipeline repository, the lines regarding the usage of os.cpu_count() are not commented out.

For LoTSS extractions, I've been using the sub-sources-outside-region.py belonging to the ddf-pipeline repository. This does not work anymore (and this is happening at least since singularity v4.0.1). Now the extraction works only with the sub-sources-outside-region.py version of this repository.

1. Does it make sense to have two versions of the same script in the two repositories?

Most of the extractions for LoTSS have been done with the sub-sources-outside-region.py in the ddf-pipeline repository, using old singularities (evidently, with singularity versions <4.0.1). My experience with this script is mostly based on that. Now I used for the first time the sub-sources-outside-region.py in this repository and noticed the slowdown. The questions are:

2. Has the version of sub-sources-outside-region.py in this repository been extensively used? Some changes were down to the script in the last 2 years, could they be responsible of the slowdown?
3. Is the slowdown really _recent_? As mentioned, I haven't never run the version of the script in this repository until 2 days ago, but what I've notice is that the script appears to run slowen that what was used to (using the script of the ddf-pipeline repository). If the reason is the getcpus() vs os.cpu_count(), this may be there for 2 years without being noticed (and that's why I ask the question above).

If it turns out that the edit was really done to solve issues on smaller nodes, that's fine...better slower but safer...

**Comment by tikk3r** [comment]
Looking at ddf-pipeline's getcpus, it has had `logical=False` for 6 years. It only takes `os.cpu_count()` when it can't find getcpus, but as long as ddf paths are set correctly it should find `utils/getcpus.py` and use the function from there, which calls the same `psutil.cpu_count(logical=False)`.

> Does it make sense to have two versions of the same script in the two repositories?

In my opinion no. It would be better if they are merged. Less to maintain and less confusion/error prone.

> Has the version of sub-sources-outside-region.py in this repository been extensively used? Some changes were down to the script in the last 2 years, could they be responsible of the slowdown?

We use it for the LoTSS subtraction in long baseline stuff. We didn't think of it as particularly slow while doing that, but we haven't exactly processed many fields. What does "slow" mean quantitively in this context?

> Is the slowdown really recent? As mentioned, I haven't never run the version of the script in this repository until 2 days ago, but what I've notice is that the script appears to run slowen that what was used to (using the script of the ddf-pipeline repository). If the reason is the getcpus() vs os.cpu_count(), this may be there for 2 years without being noticed (and that's why I ask the question above).

It doesn't seem super likely to me, given that it has been this way for 6 years at least from what I can tell. Maybe something else changed?

**Comment by botteon** [comment]
It may be even a factor of 2 slower...but note that so far  I've done only one extraction with the version in this repository...My feeling was that the DDF predict was significantly slower than in the past

**Comment by botteon** [comment]
Yessss, anyway the selfcal of LoTSS extracted targets already depends on this repository (because of facetselfcal.py). It is worth removing the sub-sources-outside-region.py in ddf-pipeline (which does not work in FLOCS) and using the one here instead. 
But I would be curious to know if the sub-sources-outside-region.py in ddf-pipeline works with the singularities used by Tim/Martin...
I retract this pull request then.

**Comment by tikk3r** [comment]
I wouldn't be surprised if specifically my containers don't work with that script, because I had to modify things in the past to make it work with recent versions of Python and NumPy, for example, so my installation isn't really an officially supported mode of operation.

**Comment by botteon** [comment]
eeek we already discussed this, see  https://github.com/mhardcastle/ddf-pipeline/issues/327

A possibility to have your containers working the LoTSS extraction is to replace the sub-sources-outside-region.py in /opt with the version of this container. This works (I already tested it)...but one also needs to change the verify=True in the scirpts that access the database (because of the SSL issue). I've seen that Martin has done some changes recently and I am not sure if these solve the issue (and/or if you clone the master ddf-pipeline version in FLOCS...)

**Comment by tikk3r** [comment]
> A possibility to have your containers working the LoTSS extraction is to replace the sub-sources-outside-region.py in /opt with the version of this container. 

Yeah that is what I do in the latest version.

> This works (I already tested it)...but one also needs to change the verify=True in the scirpts that access the database (because of the SSL issue). 

Setting that to false is not the greatest thing to do security-wise. From what I remember when Marco visited Leiden the root cause of this was something along the lines of the field not existing in the database rather than an actual SSL error I believe?

**Pull request closed without merging**
